# Generated by Django 5.2.4 on 2025-07-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('member_count', models.IntegerField()),
                ('ticket_count', models.IntegerField()),
                ('tasks_to_do_count', models.IntegerField()),
                ('tasks_high_prio_count', models.IntegerField()),
                ('owner_id', models.IntegerField()),
            ],
        ),
    ]
