# Generated by Django 5.2.4 on 2025-07-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_task_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='assignee',
        ),
    ]
